title: Steven M. Kerr | Data Scientist In-Training
description: Data Scientist In-Training
show_downloads: false

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://smkerr.github.io" # base hostname & protocol for the site


google_analytics: 298049889

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: stevekerr
image: /thumbnail-jumbo.png
#twitter:
  #username: st3v3k3rr
# consider adding social media usernames

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact'] # +cv, +portfolio
