title: Steven M. Kerr
description: MSc Data Science for Public Policy Student
show_downloads: false

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://smkerr.github.io" # base hostname & protocol for the site


google_analytics: 298049889

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%d %b %Y"

theme: # leave it empty

# social
author: smkerr
image:
email:
  username: steven.miles.k@gmail.com
linkedin:
  username: stevenmileskerr
twitter:
  username: st3v3k3rr

plugins:
  - jekyll-target-blank
  - jemoji

target-blank:
    rel: nofollow

header_page_refs: ['about', 'projects', 'now', 'cv']
